### ISSUE TITLE
为什么我怎么配置都是：安装档发生错误，请重新安装

### ISSUE THREAD

**Issue by realoldroot** [scjtqs/dnf-centos5#3]
这个错误的原因不是因为客户端Script.pvf与服务器里的不一致吗，我用同样的文件还是会出现这个问题，麻了。

**Comment by scjtqs** [comment]
客户端的pvf在统一登录器下需要加密。。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月22日(周日) 凌晨0:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [scjtqs/dnf-centos5] 为什么我怎么配置都是：安装档发生错误，请重新安装 (#3)




 
这个错误的原因不是因为客户端Script.pvf与服务器里的不一致吗，我用同样的文件还是会出现这个问题，麻了。

**Comment by realoldroot** [comment]
按照操作加密之后就提示PVF验证没通过。。是哪一步出了问题:weary::weary::weary:

**Comment by realoldroot** [comment]
我进去了！！！，但是发现服务是灰色的。。我再琢磨琢磨
