### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by yedajiang44** [scjtqs/dnf-centos5#5]
本机已有myql，所以就直接跑db.sql了，跑完吓尿了，用户表直接被干掉。。。然后用game依然无法登录数据库

还有就是dnf的容器能否添加数据库的端口号配置？

**Comment by scjtqs** [comment]
db.sql是初始化数据库用的。。。这里有俩容器，一个dnf容器，一个mysql容器。。目前没有单独配置mysql端口的配置。

**Comment by yedajiang44** [comment]
建议直接在镜像中安装一个mysql，这样的话也不需要关心数据库

那几个php可不可以搞成可执行文件？？

**Comment by scjtqs** [comment]
dnf镜像装mysql不考虑。

**Comment by yedajiang44** [comment]
刚跑了下，请问下这个是算成功了吗？？？第一次弄dnf私服，不太懂。

```
dnf    | GeoIP Allow Country Code : CN
dnf    | GeoIP Allow Country Code : HK
dnf    | GeoIP Allow Country Code : KR
dnf    | GeoIP Allow Country Code : MO
dnf    | GeoIP Allow Country Code : TW
dnf    | [!] The siroco15 channel 15('ch.15') server has been started successfully.
dnf    | Recv SIGSEGV signal --> make Dump Core file.
dnf    | Recv SIGSEGV signal --> make Dump Core file.
dnf    | ---Time : 1, 5 ----
dnf    | avgPing(0, 0, 0)
dnf    | avgPing Res(0)
dnf    | avgPing(0, 0, 0)
dnf    | avgPing Res(0)
dnf    | [01:05:55] Recv ERROR = 0 (0) : Success, MaxRead(4096) nRead(0)
dnf    | CPeer::Recv (size(-1) < 0)
dnf    | CPeer::Recv (size(-1) < 0)
dnf    | CPeer::Recv (size(-1) < 0)
dnf    | CPeer::Recv (size(-1) < 0)
dnf    | ---Time : 1, 6 ----
dnf    | avgPing(0, 0, 0)
dnf    | avgPing Res(0)
dnf    | avgPing(0, 0, 0)
dnf    | avgPing Res(0)
dnf    | ---Time : 1, 7 ----
dnf    | avgPing(0, 0, 0)
dnf    | avgPing Res(0)
dnf    | avgPing(0, 0, 0)
dnf    | avgPing Res(0)
```

**Comment by scjtqs** [comment]
算吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月25日(周三) 上午9:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [scjtqs/dnf-centos5] 数据库问题 (#5)




 
刚跑了下，请问下这个是算成功了吗？？？第一次弄dnf私服，不太懂。
 dnf    | GeoIP Allow Country Code : CN dnf    | GeoIP Allow Country Code : HK dnf    | GeoIP Allow Country Code : KR dnf    | GeoIP Allow Country Code : MO dnf    | GeoIP Allow Country Code : TW dnf    | [!] The siroco15 channel 15('ch.15') server has been started successfully. dnf    | Recv SIGSEGV signal --&gt; make Dump Core file. dnf    | Recv SIGSEGV signal --&gt; make Dump Core file. dnf    | ---Time : 1, 5 ---- dnf    | avgPing(0, 0, 0) dnf    | avgPing Res(0) dnf    | avgPing(0, 0, 0) dnf    | avgPing Res(0) dnf    | [01:05:55] Recv ERROR = 0 (0) : Success, MaxRead(4096) nRead(0) dnf    | CPeer::Recv (size(-1) < 0) dnf    | CPeer::Recv (size(-1) < 0) dnf    | CPeer::Recv (size(-1) < 0) dnf    | CPeer::Recv (size(-1) < 0) dnf    | ---Time : 1, 6 ---- dnf    | avgPing(0, 0, 0) dnf    | avgPing Res(0) dnf    | avgPing(0, 0, 0) dnf    | avgPing Res(0) dnf    | ---Time : 1, 7 ---- dnf    | avgPing(0, 0, 0) dnf    | avgPing Res(0) dnf    | avgPing(0, 0, 0) dnf    | avgPing Res(0)

**Comment by scjtqs** [comment]
默认开了两个频道，因此需要出两次5国。

**Comment by yedajiang44** [comment]
请问下有客户端的使用文档吗？？下的是高压缩率版本，解压没看到说明文件，不知所措，哈哈哈哈

**Comment by scjtqs** [comment]
emmm。。。你下载那个统一登录器吧，那里面有如何使用的文档



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月25日(周三) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [scjtqs/dnf-centos5] 数据库问题 (#5)




 
请问下有客户端的使用文档吗？？下的是高压缩率版本，解压没看到说明文件，不知所措，哈哈哈哈
